server:
  port: 8090

spring:
  application:
    name: MULTIPLE-DB-SERVICE
  #first-database
  datasource:
    url: jdbc:mysql://localhost:3306/lookup?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    trxus:
      url: jdbc:mysql://localhost:3306/transaction?useSSL=false&serverTimezone=UTC
      username: root
      password: 123456
    trxuk:
      url: jdbc:mysql://localhost:3306/transactionuk?useSSL=false&serverTimezone=UTC
      username: root
      password: 123456

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect


#    driver-class-name : com.mysql.cj.jdbc.Driver
#    database-platform : org.hibernate.dialect.MYSQLInnoDBDialect



